# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/star-admin?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
    security:
        user:
            name: root
            password: 123456
